import React, { useEffect } from "react";
import style from "./Thumbnails.module.css";
import { Card, Avatar } from 'antd';
import { useLocation } from "react-router-dom";
import jsPDF from "jspdf";
import { DownloadOutlined } from '@ant-design/icons';
import pdf1 from "./pdf1.jpg";
import pdf2 from "./pdf2.jpg";
import pdf3 from "./pdf3.jpg";

const Thumbnails = () => {

  const { Meta } = Card;
  const location = useLocation();

  const generatePdf1 = () => {
    const doc = new jsPDF();
    const { name, email, mobileNumber, bio } = location.state.userData.user;
    const headingFontSize = 20;
    const subheadingFontSize = 16;
    const bulletFontSize = 12;
    const lineHeight = 1.5;
    const pageWidth = doc.internal.pageSize.getWidth();

    // Set font styles
    doc.setFont("Montserrat", "bold"); // Change font to Montserrat
    doc.setFontSize(headingFontSize);
    doc.setTextColor("#3B3B3B"); // Adjust heading color
    doc.text("Contact Information", 15, 20);

    // Set page borders
    doc.setLineWidth(0.5);
    doc.setDrawColor("#979797");
    doc.rect(10, 10, pageWidth - 20, doc.internal.pageSize.getHeight() - 20);

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor("#979797"); // Adjust line color
    doc.line(15, 25, pageWidth - 15, 25);

    // Name
    doc.setFont("Montserrat", "bold"); // Change font to Montserrat
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor("#3B3B3B");
    doc.text("\u2022 Name:", 15, 40);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor("#000000");
    doc.setFont("Montserrat", "normal");
    doc.text(name, 40, 40);
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor("#3B3B3B");
    doc.setFont("Montserrat", "bold");
    doc.text("\u2022 Email:", 15, 50);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor("#000000");
    doc.setFont("Montserrat", "normal");
    doc.text(email, 40, 50);
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor("#3B3B3B");
    doc.setFont("Montserrat", "bold");
    doc.text("\u2022 Mobile number:", 15, 60);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor("#000000");
    doc.setFont("Montserrat", "normal");
    doc.text(mobileNumber, 60, 60);

    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(10, 70, 200, 70);

    // bio
    doc.setFont("Montserrat", "bold"); // Change font to Montserrat
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor("#3B3B3B");
    doc.text("\u2022 Bio:", 15, 80);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor("#000000");
    const bioLines = doc.splitTextToSize(bio, pageWidth - 30, { lineHeightFactor: lineHeight });
    doc.setFont("Montserrat", "normal");
    doc.text(bioLines, 15, 90, { textAlign: "justify" });

    // Footer
    const footerText = "Generated by My Website";
    const footerWidth = doc.getStringUnitWidth(footerText) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const footerX = (pageWidth - footerWidth) / 2;
    doc.setFontSize(8);
    doc.setTextColor("#BDBDBD"); // Adjust footer color
    doc.text(footerText, footerX, doc.internal.pageSize.getHeight() - 10);

    doc.save("contact-information.pdf");
  };


  const generatePdf2 = () => {
    const doc = new jsPDF();
    const { name, email, mobileNumber, bio } = location.state.userData.user;
    const headingFontSize = 20;
    const subheadingFontSize = 16;
    const bulletFontSize = 12;
    const lineHeight = 1.5;
    const pageWidth = doc.internal.pageSize.getWidth();
    const centeredX = pageWidth / 2;

    // Set font styles
    doc.setFont("OpenSans", "normal");
    doc.setTextColor(42, 61, 61);

    // Contact Information
    doc.setFontSize(headingFontSize);
    doc.setFont("OpenSans", "bold");
    doc.setTextColor(43, 46, 131);
    doc.text("Contact Information", 15, 20);

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor(43, 46, 131);
    doc.line(15, 25, pageWidth - 15, 25);

    // Name
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 171, 74);
    doc.setFont("OpenSans", "bold");
    doc.text("Name", centeredX, 40, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 44, pageWidth - 15, 44);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(name, centeredX, 55, { align: "center" });

    // Email
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 171, 74);
    doc.setFont("OpenSans", "bold");
    doc.text("Email", centeredX, 70, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 74, pageWidth - 15, 74);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(email, centeredX, 85, { align: "center" });

    // Mobile Number
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 171, 74);
    doc.setFont("OpenSans", "bold");
    doc.text("Mobile Number", centeredX, 100, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 104, pageWidth - 15, 104);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(mobileNumber, centeredX, 115, { align: "center" });

    // Bio
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 171, 74);
    doc.setFont("OpenSans", "bold");
    doc.text("Bio", centeredX, 130, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 134, pageWidth - 15, 134);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    const bioLines = doc.splitTextToSize(bio, pageWidth - 35, { lineHeightFactor: lineHeight });
    doc.setFont("OpenSans", "normal");
    doc.text(bioLines, 25, 144, { textAlign: "justify" });

    // Footer
    const footerText = "Generated by My Website";
    const footerWidth = doc.getStringUnitWidth(footerText) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const footerX = (pageWidth - footerWidth) / 2;
    doc.setFontSize(8);
    doc.setTextColor("#BDBDBD"); // Adjust footer color
    doc.text(footerText, footerX, doc.internal.pageSize.getHeight() - 10);

    doc.save("contact-information.pdf");
  };


  const generatePdf3 = () => {
    const doc = new jsPDF();
    const { name, email, mobileNumber, bio } = location.state.userData.user;
    const headingFontSize = 20;
    const subheadingFontSize = 16;
    const bulletFontSize = 12;
    const lineHeight = 1.5;
    const pageWidth = doc.internal.pageSize.getWidth();
    const centeredX = pageWidth / 2;

    // Set font styles
    doc.setFont("OpenSans", "normal");
    doc.setTextColor(42, 61, 61);

    // Contact Information
    doc.setFontSize(headingFontSize);
    doc.setFont("OpenSans", "bold");
    doc.setTextColor(43, 46, 131);
    doc.text("Contact Information", centeredX, 20, { align: "center" });

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor(43, 46, 131);
    doc.line(15, 25, pageWidth - 15, 25);

    // Name
    doc.setFillColor(255, 0, 0, 0.5);
    doc.rect(15, 35, pageWidth - 30, 7, 'F'); // draw a filled rectangle
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 255, 255);
    doc.setFont("OpenSans", "bold");
    doc.text("Name", centeredX, 40, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 44, pageWidth - 15, 44);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(name, centeredX, 55, { align: "center" });

    // Email
    doc.setFillColor(255, 0, 0, 0.5);
    doc.rect(15, 65, pageWidth - 30, 7, 'F'); // draw a filled rectangle
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 255, 255);
    doc.setFont("OpenSans", "bold");
    doc.text("Email", centeredX, 70, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 74, pageWidth - 15, 74);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(email, centeredX, 85, { align: "center" });

    // Mobile Number
    doc.setFillColor(255, 0, 0, 0.5);
    doc.rect(15, 95, pageWidth - 30, 7, 'F'); // draw a filled rectangle
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 255, 255);
    doc.setFont("OpenSans", "bold");
    doc.text("Mobile Number", centeredX, 100, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 104, pageWidth - 15, 104);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    doc.setFont("OpenSans", "normal");
    doc.text(mobileNumber, centeredX, 115, { align: "center" });

    // Bio
    doc.setFillColor(255, 0, 0, 0.5);
    doc.rect(15, 125, pageWidth - 30, 7, 'F'); // draw a filled rectangle
    doc.setFontSize(subheadingFontSize);
    doc.setTextColor(255, 255, 255);
    doc.setFont("OpenSans", "bold");
    doc.text("Bio", centeredX, 130, { align: "center" });
    doc.setLineWidth(0.3);
    doc.setDrawColor("#E7E7E7");
    doc.line(15, 134, pageWidth - 15, 134);
    doc.setFontSize(bulletFontSize);
    doc.setTextColor(43, 46, 131);
    const bioLines = doc.splitTextToSize(bio, pageWidth - 35, { lineHeightFactor: lineHeight });
    doc.setFont("OpenSans", "normal");
    doc.text(bioLines, 25, 144, { textAlign: "justify" });

    // Footer
    const footerText = "Generated by My Website";
    const footerWidth = doc.getStringUnitWidth(footerText) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const footerX = (pageWidth - footerWidth) / 2;
    doc.setFontSize(8);
    doc.setTextColor("#BDBDBD"); // Adjust footer color
    doc.text(footerText, footerX, doc.internal.pageSize.getHeight() - 10);

    doc.save("contact-information.pdf");
  };

  useEffect(() => {
    console.log(location.state.userData);
    // console.log(location.state.paraphrase);
  }, [location.state.userData])

  return (
    <div className={style.container}>
      <Card
        style={{
          width: 300,
        }}
        cover={
          <img
            alt="example"
            src={pdf1}
          />
        }
        actions={[
          <DownloadOutlined onClick={generatePdf1} />,
        ]}
      >
        <Meta
          avatar={<Avatar style={{backgroundColor:"red"}} />}
          title="Layout 1"
          description="Simple Layout"
        />
      </Card>
      <Card
        style={{
          width: 300,
        }}
        cover={
          <img
            alt="example"
            src={pdf3}
          />
        }
        actions={[
          <DownloadOutlined onClick={generatePdf2}/>,
        ]}
      >
        <Meta
          avatar={<Avatar style={{backgroundColor:"yellow"}} />}
          title="Layout 2"
          description="Colorful Layout"
        />
      </Card>
      <Card
        style={{
          width: 300,
          borderBottom: "2px solid #E7E7E7",
        }}
        cover={
          <img
            alt="example"
            src={pdf2}
          />
        }
        actions={[
          <DownloadOutlined onClick={generatePdf3}/>,
        ]}
      >
        <Meta
          avatar={<Avatar style={{backgroundColor:"green"}} />}
          title="Layout 3"
          description="highlighted Layout"
        />
      </Card>
    </div>
  )
}

export default Thumbnails;